spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: order-placed
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema:
          registry:
            url: http://localhost:8085



server:
  port: 8020

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0





springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs